#!/usr/bin/env node

const { transpile } = require('.')
const minimist = require('minimist')

const { input, output, minify, prefetch } = minimist(process.argv.slice(2), {
  string: ['input', 'output'],
  boolean: ['minify', 'prefetch'],
  alias: {
    in: 'input',
    out: 'output',
  },
  default: {
    input: process.cwd(),
    output: `${process.cwd()}/out`,
    prefetch: false,
    minify: false,
  }
});

transpile(input, output, { minify, prefetch }).then(() => {
  console.log()
  console.log(`Transpilation to ${output} has been complete`)
  console.log()
})
.catch((e) => {
  console.log()
  console.log('Transpilation has failed. Error:')
  console.log()
  console.log(e.stack)
  console.log()
})
